config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  registrations: 'users/registrations' ,
  omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'products#index'

  resources :products, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      post 'stop'
      post 'start'
    end
    collection do
      get 'search'
    end
    resources :purchases, only: [:new, :create] do
      collection do
      get 'card'
      end
    end
  end

  resources :categories, only: [:index, :show] do
    collection do
      get 'sub_category'
      get 'category'
    end
  end

  resources :brands, only: [:index, :show] do
  end

  resources :users, only: [:new, :show, :edit, :update] do
    member do
      get 'published'
      get 'trading'
      get 'sold'
      get 'buy'
      get 'bought'
    end
    collection do
      get 'signout'
    end
    resources :profiles, only: [:new]
    resources :credit_card, only: [:index, :new, :create, :destroy]
  end


end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!

  Payjp.api_key = ENV['PAYJP_SECRET_KEY']
  before_action :credit_info
#購入確認ページ
  def new
    @product = Product.find(product_params[:product_id])
  end

#購入完了ページ
  def create
    @product = Product.find(product_params[:product_id])
    if @credit_info == nil
      render action: :new
    elsif current_user.id == @credit_info.user_id
      @charge = Payjp::Charge.create(
      :amount => @product.price,
      :customer => @credit_info.customer_id,
      :currency => 'jpy',
      )
      Purchase.create(user_id: current_user.id, product_id: @product.id, total_payment: @product.price)
      @product.update(status: 3)
      redirect_to root_path
      
    end
  end

  def card
  end


  private
  def product_params
    params.permit(:product_id)
  end

  def credit_info
    @credit_info = CreditCard.find_by(user_id: current_user.id)
    if @credit_info
      @customer = Payjp::Customer.retrieve(@credit_info.customer_id)
      @card = @customer.cards.retrieve(@credit_info.card_id)
    end
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/card.html.haml
.single-container
  = render 'shared/logo-header'
  %main.single-main
    %section.l-single-container.buy-item-container
      %h2.creditcard-form__title
        支払い方法
      = form_tag( "/users/#{current_user.id}/credit_card", method: "POST", class: "creditcard-form__body", id:"add-card" ) do 
        - if @card 
          %section
            .single-content
              %h3.purchase-method-header__title 
                クレジットカード一覧
            %ul.payment-method__content__list
              %li.transact-card
                .card-info.single-content
                  .setting-card
                    %figure
                      = render 'shared/card-images'
                    .transact-card__payment-num 
                      = "************" + @card.last4
                    .transact-card__payment-num
                      = "#{@card.exp_month} / #{@card.exp_year.to_s.slice(0..1).to_i}"
          %section.payment-method-card-submit
            .single-content
              = link_to "次に進む",  new_product_purchase_path(params[:product_id]), class:"btn-red"

        - else
          .creditcard-form__container
            .form-group-card-num
              %label.form-group-card-num__label カード番号
              %span.form-group-card-num__badge
                必須
              = text_field :name, '', maxlength:'16', class:'form-group-card-num__input', id:'payment_card_no', placeholder:'半角数字のみ'
              %ul.form-group-card-num__card-lists.clearfix
                %li.card-list
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?2845599746", class: "card-list__image"
                %li.card-list
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?2845599746", class: "card-list__image"
                %li.card-list
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?2845599746", class: "card-list__image"
                %li.card-list
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?2845599746", class: "card-list__image"
                %li.card-list
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?2845599746", class: "card-list__image"
                %li.card-list
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?2845599746", class: "card-list__image"
                %li.card-list
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?2845599746", class: "card-list__image"
            .form-group-card-expire
              %label.form-group-card-expire__label
                有効期限
              %span.form-group-card-expire__badge
                必須
              .form-group-card-expire__wrap
                = select_tag('exp_month', options_for_select((01...13)), id:"payment_card_expire_mm", class:"form-group-card-expire__input select-default")
                %span
                  月
              .form-group-card-expire__wrap
                = select_tag('exp_year', options_for_select((DateTime.now.year..2029)), id:"payment_card_expire_yy", class:"form-group-card-expire__input select-default") 
                %span
                  年
            .form-group-card-code
              %label.form-group-card-code__label
                セキュリティコード
              %span.form-group-card-code__badge
                必須
              %input.form-group-card-num__input#security_code{ name: "cvc", type:"text", placeholder:"カード背面4桁もしくは3桁の番号", maxlength: "3" }
              .form-group-card-code__explain
                %span.form-group-card-code__explain--question
                  ?
                カード裏面の番号とは
              .form-group-card-code__is-show-wrap#securityCode-modal
                .form-group-card-code__is-show
                  カードの裏面をご参照ください。
                  %br/
                  %img.form-group-card-code__is-show--image{ src: "//www-mercari-jp.akamaized.net/assets/img/signup/seq-card.png?2845599746" }
              = button_tag "追加する", {class:"form-group-card-submit"}

= render 'shared/logo-footer'

app/views/purchases/new.html.haml
.single-container
  = render 'shared/logo-header'
  %main.single-main
    %section.l-single-container.buy-item-container
      %h2.l-single-head 購入を確定しますか？
      %section.buy-content.buy-item
        .buy-content-inner
          %h3.buy-item-image
            = image_tag @product.product_images[0].image, :width => "160", :height => "160"
          %p.buy-item-name.bold 
            = @product.name
          .buy-form
            %p.buy-price-ja.bold
              = "¥ #{@product.price}"
              %span.item-shipping-fee.f14.bold 送料込み
            %ul.buy-accordion.not-have
              %li.accordion-parent
                .accordion-toggle
                  ポイントはありません
            %ul.buy-price-table
              %li.buy-price-row.buy-you-pay.bold
                .buy-price-cell 支払い金額
                .buy-price-cell
                  %span{"data-buy-pay" => ""}
                  = "¥ #{@product.price}"
            = link_to "購入する", product_purchases_path(params[:product_id]), method: :post, class:"button btn-default btn-red bold"

      %section.buy-content.buy-user-info
        .buy-content-inner
          %h3 配送先
          %address.buy-user-info-text
            〒144-0052
            %br/
            東京都 大田区 多摩川 土手 114-514
            %br/
            ピェェヌ ぬき
          %p.buy-user-info-text
          = link_to  new_user_profile_path(current_user.id) , class: "buy-user-info-fix" do
            %span 変更する
            = fa_icon 'angle-right'
      %section.buy-content.buy-user-info{"data-buy" => "pay-method"}
        .buy-content-inner
          %h3 支払い方法
          -if @card 
            %p.buy-user-info-text
              = "************" + "#{@card.last4}"
              %br/
              = "#{@card.exp_month} / #{@card.exp_year.to_s.slice(0..1).to_i}"
            %figure
              = render 'shared/card-images'
          - else
            %p.buy-user-info-text
              %br/
              \/
          %p
          = link_to card_product_purchases_path(params[:product_id]), class: "buy-user-info-fix" do
            %span 変更する
            = fa_icon 'angle-right'
  = render 'shared/logo-footer'