config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  registrations: 'users/registrations' ,
  omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'products#index'

  resources :products, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      post 'stop'
      post 'start'
    end
    collection do
      get 'search'
    end
    resources :purchases, only: [:new, :create] do
      collection do
      get 'card'
      end
    end
  end

  resources :categories, only: [:index, :show] do
    collection do
      get 'sub_category'
      get 'category'
    end
  end

  resources :brands, only: [:index, :show] do
  end

  resources :users, only: [:new, :show, :edit, :update] do
    member do
      get 'published'
      get 'trading'
      get 'sold'
      get 'buy'
      get 'bought'
    end
    collection do
      get 'signout'
    end
    resources :profiles, only: [:new]
    resources :credit_card, only: [:index, :new, :create, :destroy]
  end


end

app/models/adress.rb
class Adress < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :products
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
  scope :main_category, -> { where(main_category_id: nil) }
  scope :sub_category, -> (main){ where(sub_category_id: nil).where('main_category_id is not NULL').where(main_category: main) }
  scope :category, -> (sub){ where(sub_category: sub) }

  has_many :category, class_name: "Category",foreign_key: "main_category_id"
  has_many :category, class_name: "Category",foreign_key: "sub_category_id"
  belongs_to :main_category, class_name: "Category", optional: true
  belongs_to :sub_category, class_name: "Category", optional: true
  has_many :products
  has_ancestry
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true, uniqueness: true
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :area
  belongs_to :product_size
  belongs_to :brand, optional: true
  accepts_nested_attributes_for :brand, reject_if: :reject_brand_blank, allow_destroy: true
  has_many :product_images, dependent: :delete_all
  accepts_nested_attributes_for :product_images, reject_if: :reject_image_no_change, allow_destroy: true, limit: 10
  belongs_to :category
  has_many :purchases
  has_many :users, through: :purchases

  enum condition:       {"新品、未使用": 0, "未使用に近い": 1, "目立った傷や汚れなし": 2, "やや傷や汚れあり": 3, "傷や汚れあり": 4, "全体的に状態が悪い": 5}

  enum shipping_method: {"未定": 0, "らくらくメルカリ便": 1, "ゆうメール": 2, "レターパック": 3, "普通郵便(定形、定形外)": 4, "クロネコヤマト": 5, "ゆうパック": 6, "クリックポスト": 7, "ゆうパケット": 8}

  enum shipping_burden: {"送料込み(出品者負担)": 0, "着払い(購入者負担)": 1}

  enum estimated_date: {"1~2日で発送": 0, "2~3日で発送": 1, "4~7日で発送": 2}

  enum status: {published: 0, stopped: 1, trading: 2, sold: 3}

  validates :name, length: { maximum: 40 }, presence: true
  validates :description, length: { maximum: 1000 }, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }, presence: true
  validates :area_id, presence: true
  validates :condition, presence: true
  validates :product_size_id, presence: true
  validates :shipping_method, presence: true
  validates :shipping_burden, presence: true
  validates :estimated_date, presence: true
  validates :user_id, presence: true
  validates :product_images, length: { minimum: 1, maximum: 10 }

  def reject_brand_blank(attributes)
    exists = Brand.find_by(name: attributes[:name]).present?
    empty = attributes[:name].blank?
    exists || empty
  end

  def reject_image_no_change(attributes)
    exists = ProductImage.find_by(id: attributes[:id]).present?
    destory = attributes[:image_cache].nil?
    empty = attributes[:image].blank?
    if exists
      attributes.merge!(_destroy: 1) if destory
      return !destory
    else
      return empty
    end
  end

  def new_brand(brand_name)
    self.brand = Brand.find_by(name: brand_name) if Brand.find_by(name: brand_name)
    self.save
  end

  def self.find_products_match_category(category)
    if category.main_category_id.nil? && category.sub_category_id.nil?
      self.joins(:category).merge(Category.where(main_category_id: category.id)).order("created_at DESC")
    elsif category.main_category_id.present? && category.sub_category_id.nil?
      self.joins(:category).merge(Category.where(sub_category_id: category.id)).order("created_at DESC")
    end
  end

end

app/models/product_comment.rb
class ProductComment < ApplicationRecord
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  mount_uploader :image, ProductImagesUploader
  belongs_to :product, optional: true
end

app/models/product_size.rb
class ProductSize < ApplicationRecord
  has_many :products
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  has_one :credit_cards
  has_many :purchases
  has_many :products, through: :purchases
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable, :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  validates :nickname, length: { maximum: 20 }
  validates :password, length: { minimum: 6 },allow_nil: true
  validates :nickname, presence: true
  validates :uid, :uniqueness => {:scope => :provider},allow_blank: true

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        nickname:     auth.info.name,
        email:    auth.info.email,
        password: Devise.friendly_token[0, 20]
      )
    end

    user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :new
  before_action :set_user, only: [:edit, :update, :published, :trading, :sold, :buy, :bought]
  def new
  end


  def show
  end

  def edit

  end

  def update
    if @user.id == current_user.id
      @user.update(user_params)
    end
    redirect_to action: :edit
  end

  def signout
  end

  def identification
  end

  def published
    @products = @user.products.where(status: 'published').or(@user.products.where(status: 'stopped'))
  end

  def trading
    @products = @user.products.trading
  end

  def sold
    @products = @user.products.sold
  end

  def buy 
    @products = @user.products.trading
  end

  def bought
    products_number = @user.purchases[0].product_id
    @products = Product.find(products_number)
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :introduction)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title メルカリ スマホでかんたん フリマアプリ
    %script{:src => "https://js.pay.jp/", :type => "text/javascript"}
    %link{:href => "https://use.fontawesome.com/releases/v5.6.1/css/all.css", :rel => "stylesheet"}/
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/shared/_appbanner.html.haml
%aside.app-banner
  .app-banner__inner
    .app-banner__inner--left
      %h2 スマホでかんたんフリマアプリ
      %p 今すぐ無料ダウンロード！
      .app-banner__inner--icon
        %figure
          %img{:src => "https://www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?2855175014", :width => "68"}/
        %ul.clearfix
          %li
            %a{:href => "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8", :target => "_blank"}
              %img{:height => "40", :src => "https://www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?2855175014", :width => "133"}/
          %li
            %a{:href => "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja", :target => "_blank"}
              %img{:height => "40", :src => "https://www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?2855175014", :width => "133"}/
    .app-banner__inner--right
      %img{:src => "https://www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?2855175014", :width => "300"}

app/views/shared/_card-images.html.haml
- if @card.brand == "Visa"
  = image_tag("//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?3703848211", alt: "visa", height: "19", width: "49")
- elsif @card.brand == "MasterCard"
  = image_tag("//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?3703848211", alt: "master", height: "30", width: "49")
- elsif @card.brand == "Discover"
  = image_tag("//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?3703848211", alt: "discover", height: "30", width: "49")
- elsif @card.brand == "American Express"
  = image_tag("//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?3703848211", alt: "american", height: "30", width: "49")
- elsif @card.brand == "JCB"
  = image_tag("//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?3703848211", alt: "jcb", height: "30", width: "49")
- elsif @card.brand == "Diners Club"
  =  image_tag("//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?3703848211", alt: "jcb", height: "30", width: "49")
- else
  = image_tag("//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?3703848211", alt: "saison", height: "30", width: "49")

app/views/shared/_content-left.html.haml
%nav.mypage-nav
  %ul.mypage-nav__list
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/"}
        マイページ
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/notification/"}
        お知らせ
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/todo/"}
        やることリスト
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/like/history/"}
        いいね！一覧
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/sell/"}
        出品する
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/listings/listing/"}
        出品した商品 - 出品中
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/listings/in_progress/"}
        出品した商品 - 取引中
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/listings/completed/"}
        出品した商品 - 売却済み
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/purchase/"}
        購入した商品 - 取引中
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/purchased/"}
        購入した商品 - 過去の取引
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/news/"}
        ニュース一覧
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/review/history/"}
        評価一覧
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/help_center/"}
        ガイド
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/support/"}
        お問い合わせ
        = fa_icon "angle-right"


  %h3.mypage-nav__head メルペイ
  %ul.mypage-nav__list
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/sales/"}
        売上・振込申請
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/point/"}
        ポイント
        = fa_icon "angle-right"


  %h3.mypage-nav__head 設定
  %ul.mypage-nav__list
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/profile/"}
        プロフィール
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/deliver_address/"}
        発送元・お届け先住所変更
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/card/"}
        支払い方法
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/email_password/"}
        メール/パスワード
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/identification/"}
        本人情報
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/mypage/sms_confirmation/"}
        電話番号の確認
        = fa_icon "angle-right"
    %li
      %a.mypage-nav__list__item{:href => "/jp/logout/"}
        ログアウト
        = fa_icon "angle-right"

app/views/shared/_footer.html.haml
%footer.footerAll
  %nav
    %ul
      %li.footerAll__cell
        %h2.footerAll__cell--head メルカリについて
        %ul
          %li
            %a{:href => "https://about.mercari.com/"} 会社概要（運営会社）
          %li
            %a{:href => "https://www.mercari.com/jp/privacy/"} プライバシーポリシー
          %li
            %a{:href => "https://www.mercari.com/jp/tos/"} メルカリ利用規約
          %li
            %a{:href => "https://www.mercari.com/jp/tos_paid_point/"} 有償ポイントに関する特約
          %li
            %a{:href => "https://www.mercari.com/jp/tos_smartphone_support/"} あんしんスマホサポート制度に関する利用特約
          %li
            %a{:href => "https://www.mercari.com/jp/compliance/"} コンプライアンスポリシー
          %li
            %a{:href => "https://www.mercari.com/jp/data_security/"} 個人データの安全管理に係る基本方針
          %li
            %a{:href => "https://www.mercari.com/jp/tokutei/"} 特定商取引に関する表記
          %li
            %a{:href => "https://www.mercari.com/jp/shikin_kessai/"} 資金決済法に基づく表示
          %li
            %a{:href => "https://about.mercari.com/csr/safety/"} 法令順守と犯罪抑止のために
          %li
            %a{:href => "https://www.mercari.com/jp/jobs/"} 採用情報
      %li.footerAll__cell
        %h2.footerAll__cell--head メルカリを見る
        %ul
          %li
            %a{:href => "https://www.mercari.com/jp/category/"} カテゴリー一覧
          %li
            %a{:href => "https://www.mercari.com/jp/brand/"} ブランド一覧
          %li
            %a{:href => "https://www.mercari.com/jp/area/"} 出品地域一覧
          %li
            %a{:href => "https://jp-news.mercari.com/", :target => "_blank"} 公式ブログ
          %li
            %a{:href => "https://twitter.com/mercari_jp", :target => "_blank"} 公式Twitter
          %li
            %a{:href => "https://www.facebook.com/mercarijp", :target => "_blank"} 公式Facebook
      %li.footerAll__cell
        %h2.footer__cell--head ヘルプ＆ガイド
        %ul
          %li
            %a{:href => "https://www.mercari.com/jp/help_center/"} メルカリガイド
          %li
            %a{:href => "https://www.mercari.com/jp/logo-guidelines/"} メルカリロゴ利用ガイドライン
          %li
            %a{:href => "https://about.mercari.com/press/news/"} お知らせ
          %li
            %a{:href => "https://www.mercari.com/jp/rakuraku-mercari/"} らくらくメルカリ便とは
          %li
            %a{:href => "https://www.mercari.com/jp/yuyu-mercari/"} ゆうゆうメルカリ便とは
          %li
            %a{:href => "https://www.mercari.com/jp/rakuraku-ogata/"} 大型らくらくメルカリ便とは
          %li
            %a{:href => "https://www.mercari.com/jp/guide/car/"} 車体取引ガイド
          %li
            %a{:href => "https://www.mercari.com/jp/refund-returns/"} 返品・返金ポリシー
          %li
            %a{:href => "https://www.mercari.com/jp/safe/description/", :target => "_blank"} メルカリあんしん・あんぜん宣言！
          %li
            %a{:href => "https://www.mercari.com/jp/authenticity/"} 偽ブランド品撲滅への取り組み
          %li
            %a{:href => "https://www.mercari.com/jp/box/"} メルカリボックス
      %li.footerAll__cell
        %h2.footer__cell--head 国
        %ul
          %li
            %a{:href => "https://www.mercari.com/"}
              %img{:alt => "", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/flag_us.png?2855175014", :width => "22"}>/
              United States
          %li
            %a{:href => "https://www.mercari.com/uk/"}
              %img{:alt => "", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/flag_uk.png?2855175014", :width => "22"}>/
              United Kingdom
          %li
            %a.active{:href => "https://www.mercari.com/jp/"}
              %img{:alt => "", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/flag_jp.png?2855175014", :width => "22"}>/
              日本
  = link_to root_path, class: "footer-logo" do
    %img{:alt => "mercari", :height => "33", :src => "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?2855175014", :width => "124"}/
  %p.footer-copyright
    %small © 2019 Mercari

app/views/shared/_header.html.haml
%header.pc-header
  .pc-header__inner
    %h1.logo-left
      = link_to root_path do
        = image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?1445690901")
    = form_tag(search_products_path, method: :get,class: "pc-header__form",enforce_utf8: false ) do
      %input.input-default{:name => "keyword", :placeholder => "キーワードから探す", :type => "search", :value => ""}/
      %button{class: "pc-header__form--btn",:type => "submit"}
        %i.fas.fa-search
    .pc-header__navbox.clearfix
      .dropbox
        %ul.pc-header__nav.clearfix
          %li
            %h2#category-find-btn
              = link_to root_path ,class: "pc-header__nav-root" do
                カテゴリーから探す
          %li#brand-find-btn
            %h2
              = link_to root_path ,class: "pc-header__nav-root" do
                ブランドから探す
      .loginRegister
        %ul.pc-header__login-nav
        - if user_signed_in?
          %li
            = link_to user_path(current_user.id), class: "pc-header-nav-root" do
              マイページ
          %li
            = link_to destroy_user_session_path, method: :delete,class: "pc-header-logout" do
              ログアウト
        - else
          %li
            = link_to new_user_session_path, class: "pc-header__btn--btn-red" do
              ログイン
          %li
            = link_to new_user_path, class: "pc-header__btn--signup" do
              新規会員登録
      .category-list-box.clearfix.category-list-box-hidden
        %ul.main-category-lists
          %li.main-category.main-category#main-category-1
            = link_to "レディース", category_path(1), class: "main-category__link", id: "main-category-link-1"
          %li.main-category#main-category-2
            = link_to "メンズ", category_path(2), class: "main-category__link", id: "main-category-link-2"
          %li.main-category#main-category-3
            = link_to "ベビー・キッズ", category_path(3), class: "main-category__link", id: "main-category-link-3"
          %li.main-category#main-category-4
            = link_to "インテリア・住まい・小物", category_path(4), class: "main-category__link", id: "main-category-link-4"
          %li.main-category#main-category-5
            = link_to "本・音楽・ゲーム", category_path(5), class: "main-category__link", id: "main-category-link-5"
          %li.main-category#main-category-6
            = link_to "おもちゃ・ホビー・グッズ", category_path(6), class: "main-category__link", id: "main-category-link-6"
          %li.main-category#main-category-7
            = link_to "コスメ・香水・美容", category_path(7), class: "main-category__link", id: "main-category-link-7"
          %li.main-category#main-category-8
            = link_to "家電・スマホ・カメラ", category_path(8), class: "main-category__link", id: "main-category-link-8"
          %li.main-category#main-category-9
            = link_to "スポーツ・レジャー", category_path(9), class: "main-category__link", id: "main-category-link-9"
          %li.main-category#main-category-10
            = link_to "ハンドメイド", category_path(10), class: "main-category__link", id: "main-category-link-10"
          %li.main-category#main-category-11
            = link_to "チケット", category_path(11), class: "main-category__link", id: "main-category-link-11"
          %li.main-category#main-category-12
            = link_to "自動車・オートバイ", category_path(12), class: "main-category__link", id: "main-category-link-12"
          %li.main-category#main-category-13
            = link_to "その他", category_path(13), class: "main-category__link", id: "main-category-link-13"
          %li.main-category#main-category-14
            = link_to "カテゴリー一覧", "#", class: "main-category__link"

app/views/shared/_logo-footer.html.haml
%footer.single-footer
  %nav
    %ul.clearfix
      %li
        = link_to root_path do
          プライバシーポリシー
      %li
        = link_to root_path do
          メルカリ利用規約
      %li
        = link_to root_path do
          特定商取引に関する表記
  = link_to root_path , class: "single-footer-logo" do
    %img{:alt => "mercari", :height => "65", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?2855175014", :width => "80"}/
  %p
    %small © 2019 Mercari

app/views/shared/_logo-header.html.haml
%header.single-header
  %h1
    = link_to root_path do
      %img{:alt => "mercari", :src => "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?128691313"}/

app/views/shared/_mypage-sidebar.html.haml
.mypage-body__sidebar
  %nav.mypage-nav
    %ul.mypage-nav__list
      %li
        = link_to user_path(current_user.id), class: "mypage-nav__list__item" do
          マイページ
          = fa_icon "angle-right"
      %li
        = link_to "#", class: "mypage-nav__list__item" do
          お知らせ
          = fa_icon "angle-right"
      %li
        = link_to "#", class: "mypage-nav__list__item" do
          やることリスト
          = fa_icon "angle-right"
      %li
        = link_to "#", class: "mypage-nav__list__item" do
          いいね！一覧
          = fa_icon "angle-right"
      %li
        = link_to new_product_path, class: "mypage-nav__list__item" do
          出品する
          = fa_icon "angle-right"
      %li
        = link_to published_user_path(current_user.id), class: "mypage-nav__list__item" do
          出品した商品 - 出品中
          = fa_icon "angle-right"
      %li
        = link_to trading_user_path(current_user.id), class: "mypage-nav__list__item" do
          出品した商品 - 取引中
          = fa_icon "angle-right"
      %li
        = link_to sold_user_path(current_user.id), class: "mypage-nav__list__item" do
          出品した商品 - 売却済み
          = fa_icon "angle-right"
      %li
        = link_to buy_user_path(current_user.id), class: "mypage-nav__list__item" do
          購入した商品 - 取引中
          = fa_icon "angle-right"
      %li
        = link_to bought_user_path(current_user.id), class: "mypage-nav__list__item" do
          購入した商品 - 過去の取引
          = fa_icon "angle-right"
      %li
        = link_to "#", class: "mypage-nav__list__item" do
          ニュース一覧
          = fa_icon "angle-right"
      %li
        = link_to "#", class: "mypage-nav__list__item" do
          評価一覧
          = fa_icon "angle-right"
      %li
        = link_to "#", class: "mypage-nav__list__item" do
          ガイド
          = fa_icon "angle-right"
      %li
        = link_to "#", class: "mypage-nav__list__item" do
          お問い合わせ
          = fa_icon "angle-right"


    %h3.mypage-nav__head メルペイ
    %ul.mypage-nav__list
      %li
        = link_to "#", class: "mypage-nav__list__item" do
          売上・振込申請
          = fa_icon "angle-right"
      %li
        = link_to "#", class: "mypage-nav__list__item" do
          ポイント
          = fa_icon "angle-right"


    %h3.mypage-nav__head 設定
    %ul.mypage-nav__list
      %li
        = link_to edit_user_path(current_user.id), class: "mypage-nav__list__item" do
          プロフィール
          = fa_icon "angle-right"
      %li
        = link_to "#", class: "mypage-nav__list__item" do
          発送元・お届け先住所変更
          = fa_icon "angle-right"
      %li
        = link_to user_credit_card_index_path(current_user.id), class: "mypage-nav__list__item" do
          支払い方法
          = fa_icon "angle-right"
      %li
        = link_to "#", class: "mypage-nav__list__item" do
          メール/パスワード
          = fa_icon "angle-right"
      %li
        = link_to new_user_profile_path(current_user.id), class: "mypage-nav__list__item" do
          本人情報
          = fa_icon "angle-right"
      %li
        = link_to "#", class: "mypage-nav__list__item" do
          電話番号の確認
          = fa_icon "angle-right"
      %li
        = link_to signout_users_path, class: "mypage-nav__list__item" do
          ログアウト
          = fa_icon "angle-right"

app/views/shared/_product.html.haml
= link_to product_path(product.id), class: "products-list-item-box" do
  - if product.product_images.present?
    = image_tag product.product_images.first.image ,class: "products-list-item-box__image"
  - else
    = image_tag "http://www.familys-talk.com/wp-content/themes/refinepro/img/noimage.png.pagespeed.ce.9JwMGwgNY4.png" ,class: "products-list-item-box__image"
  .products-list-item-box__body
    .items-box__body--details.item-details.clearfix
      %h3.item-details__name
        = product.name
      .item-details__num.clearfix
        .item-details__num--price
          = "￥ " + product.price.to_s(:delimited)
        .item-details__num--liked
          = fa_icon "heart-o", text:"12"
      .item-details__tax
        (税込み)

app/views/shared/_relation_category.html.haml
%li.associations-links__link
  = link_to relation_category.name, category_path(relation_category.id)

app/views/shared/_sellbtn.html.haml
-if user_signed_in?
  = link_to new_product_path, class: "footer-sell-btn" do
    %div 出品
    %i.fas.fa-camera
-else
  = link_to new_user_session_path, class: "footer-sell-btn" do
    %div 出品
    %i.fas.fa-camera