config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  registrations: 'users/registrations' ,
  omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'products#index'

  resources :products, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      post 'stop'
      post 'start'
    end
    collection do
      get 'search'
    end
    resources :purchases, only: [:new, :create] do
      collection do
      get 'card'
      end
    end
  end

  resources :categories, only: [:index, :show] do
    collection do
      get 'sub_category'
      get 'category'
    end
  end

  resources :brands, only: [:index, :show] do
  end

  resources :users, only: [:new, :show, :edit, :update] do
    member do
      get 'published'
      get 'trading'
      get 'sold'
      get 'buy'
      get 'bought'
    end
    collection do
      get 'signout'
    end
    resources :profiles, only: [:new]
    resources :credit_card, only: [:index, :new, :create, :destroy]
  end


end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :area
  belongs_to :product_size
  belongs_to :brand, optional: true
  accepts_nested_attributes_for :brand, reject_if: :reject_brand_blank, allow_destroy: true
  has_many :product_images, dependent: :delete_all
  accepts_nested_attributes_for :product_images, reject_if: :reject_image_no_change, allow_destroy: true, limit: 10
  belongs_to :category
  has_many :purchases
  has_many :users, through: :purchases

  enum condition:       {"新品、未使用": 0, "未使用に近い": 1, "目立った傷や汚れなし": 2, "やや傷や汚れあり": 3, "傷や汚れあり": 4, "全体的に状態が悪い": 5}

  enum shipping_method: {"未定": 0, "らくらくメルカリ便": 1, "ゆうメール": 2, "レターパック": 3, "普通郵便(定形、定形外)": 4, "クロネコヤマト": 5, "ゆうパック": 6, "クリックポスト": 7, "ゆうパケット": 8}

  enum shipping_burden: {"送料込み(出品者負担)": 0, "着払い(購入者負担)": 1}

  enum estimated_date: {"1~2日で発送": 0, "2~3日で発送": 1, "4~7日で発送": 2}

  enum status: {published: 0, stopped: 1, trading: 2, sold: 3}

  validates :name, length: { maximum: 40 }, presence: true
  validates :description, length: { maximum: 1000 }, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }, presence: true
  validates :area_id, presence: true
  validates :condition, presence: true
  validates :product_size_id, presence: true
  validates :shipping_method, presence: true
  validates :shipping_burden, presence: true
  validates :estimated_date, presence: true
  validates :user_id, presence: true
  validates :product_images, length: { minimum: 1, maximum: 10 }

  def reject_brand_blank(attributes)
    exists = Brand.find_by(name: attributes[:name]).present?
    empty = attributes[:name].blank?
    exists || empty
  end

  def reject_image_no_change(attributes)
    exists = ProductImage.find_by(id: attributes[:id]).present?
    destory = attributes[:image_cache].nil?
    empty = attributes[:image].blank?
    if exists
      attributes.merge!(_destroy: 1) if destory
      return !destory
    else
      return empty
    end
  end

  def new_brand(brand_name)
    self.brand = Brand.find_by(name: brand_name) if Brand.find_by(name: brand_name)
    self.save
  end

  def self.find_products_match_category(category)
    if category.main_category_id.nil? && category.sub_category_id.nil?
      self.joins(:category).merge(Category.where(main_category_id: category.id)).order("created_at DESC")
    elsif category.main_category_id.present? && category.sub_category_id.nil?
      self.joins(:category).merge(Category.where(sub_category_id: category.id)).order("created_at DESC")
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show, :search]
before_action :set_product, only: [:edit, :update, :destroy, :stop, :start]
#トップページ
  def index
    @ladies = Category.find(1)
    @mens = Category.find(2)
    @baby = Category.find(3)
    @cosme = Category.find(7)
    @ladies_item = Product.joins(:category).merge(Category.where(main_category_id: 1)).limit(4).order(id: "DESC")
    @mens_item = Product.joins(:category).merge(Category.where(main_category_id: 2)).limit(4).order(id: "DESC")
    @baby_item = Product.joins(:category).merge(Category.where(main_category_id: 3)).limit(4).order(id: "DESC")
    @cosme_item = Product.joins(:category).merge(Category.where(main_category_id: 7)).limit(4).order(id: "DESC")
    @chanel = Brand.find(1)
    @vuitton = Brand.find(2)
    @supreme = Brand.find(3)
    @nike = Brand.find(4)
    @chanel_item = Product.where(brand_id: 1).limit(4).order(id: "DESC")
    @vuitton_item = Product.where(brand_id: 2).limit(4).order(id: "DESC")
    @supreme_item = Product.where(brand_id: 3).limit(4).order(id: "DESC")
    @nike_item = Product.where(brand_id: 4).limit(4).order(id: "DESC")
  end

#商品詳細ページ
  def show
    @product = Product.find(params[:id])
    @other_product_previous = Product.order(id: "DESC").where("id < ?", params[:id]).first
    @other_product_next = Product.order(id: "DESC").where("id > ?", params[:id]).reverse.first
    @user_other_products = Product.where("(user_id = ?) AND (status = ?)", @product.user_id, 0).where.not(id: params[:id]).limit(6)
    @other_products = Product.where("brand_id = ?", @product.brand_id).joins(:category).merge(Category.where("sub_category_id = ?" , @product.category.sub_category_id)).where.not(id: params[:id]).limit(6)
    @other_products_no_brand = Product.joins(:category).merge(Category.where("sub_category_id = ?" , @product.category.sub_category_id)).where.not(id: params[:id]).limit(6)
  end

#商品検索機能
  def search
    @search = Product.ransack(params[:q])
    @products = @search.result
    # @products = Product.where('name LIKE(?)', "%#{params[:keyword]}%")
    @search.build_sort if @search.sorts.empty?
  end

#商品出品ページ
  def new
    @product = Product.new
    @product.product_images.build
    @product.build_brand
  end

#トップページへリダイレクト
  def create
    @product = Product.new(product_params)
    if @product.save
      @product.new_brand(params[:product][:brand_attributes][:name]) if params[:product][:brand_attributes][:name].present?
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @product_images = @product.product_images
    @product_sales_fee = ( @product.price * 0.1 ).floor
    @product_sales_profit = @product.price - @product_sales_fee
    @product_images.each do |product_image|
      product_image.image.cache!
    end
    @product.build_brand if @product.brand_id.nil?
  end

  def update
    if @product.user_id == current_user.id
      if @product.brand_id.present?
        @product.new_brand(params[:product][:brand_attributes][:name]) if @product.brand.name != params[:product][:brand_attributes][:name]
      else
        @product.new_brand(params[:product][:brand_attributes][:name]) if params[:product][:brand_attributes][:name].present?
      end
      if @product.update_attributes(product_params)
        brand_null_update
        redirect_to root_path
      else
        @product_images = @product.product_images
        @product.build_brand if @product.brand_id.nil?
        render :edit
      end
    end
  end

  def destroy
    if @product.user == current_user
      @product.destroy
    end
    redirect_to root_path
  end

  def stop
    @product.status = 'stopped'
    @product.save
    render :show
  end

  def start
    @product.status = 'published'
    @product.save
    render :show
  end

private
  def product_params
    params.require(:product).permit(:name, :description, :category_id, :product_size_id, :brand_id, :condition, :shipping_method, :shipping_burden, :area_id, :estimated_date, :price, product_images_attributes:[:id, :image, :image_cache], brand_attributes:[:id, :name]).merge(user_id: current_user.id)
  end

  def brand_null_update
    @product.brand_id = nil if params[:product][:brand_attributes][:id].present? && params[:product][:brand_attributes][:name].blank?
    @product.save
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_prodcut_image_thumbnail.html.haml
- if prodcut_image_thumbnail.image.url.present?
  %li.sell-upload-file
    = image_tag prodcut_image_thumbnail.image ,class:"sell-upload-file__image"
    .sell-upload-file__buttons.clearfix
      %button.sell-upload-file__buttons--button
        編集
      = button_tag "削除", class: "sell-upload-file__buttons--button--delete exist-image", id: "delete-button-#{prodcut_image_thumbnail_counter}"

app/views/products/_product.html.haml
= link_to product_path(product.id), class: "assosiation-items__items-box items-box" do
  -if product.product_images.present?
    = image_tag product.product_images.first.image ,class: "items-box__image"
  -else
    = image_tag "http://www.familys-talk.com/wp-content/themes/refinepro/img/noimage.png.pagespeed.ce.9JwMGwgNY4.png" ,class: "items-box__image"
  .items-box__body
    .items-box__body--details.item-details.clearfix
      %h3.item-details__name
        = product.name
      .item-details__num.clearfix
        .item-details__num--price
        ¥
        = number_with_delimiter("#{product.price}")
        .item-details__num--liked
          = fa_icon "heart-o", text:"189"
      .item-details__tax
        (税込)

app/views/products/index.html.haml
.default-container

  = render 'shared/header'

  %section
    .top-appbanner
      .top-appbanner__slides
        %div
          .top-appbanner__slides--inner-left
            %h2
              スマホでかんたん
              %br
              フリマアプリ
            %p
              メルカリはスマホカメラからすぐに出品できる
              %br
              購入時も安心な独自システムのアプリです
            .storelogo
              = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8" do
                = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?4136293187"
              = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja" do
                = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?4136293187"
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/jp/top/main_content_pc.png?4136293187",class: "iphone-picture"
      .top-appbanner__slides--newlife
        = link_to "",root_path,class: "top-banner banner-new-life"
      .top-appbanner__slides--heisei
        = link_to "",root_path,class: "top-banner banner-bokurano-heisei"
  %section.pickup-container
    %h2.pickup-head ピックアップカテゴリー
    %section.items-box-container.clearfix
      %h3.items-box-container__title
        = link_to "#{@ladies.name} 新着アイテム", category_path(@ladies.id)
      .items-box-content.clearfix
        = render partial: "product", collection: @ladies_item
      .view-all
        = link_to "すべての商品を見る", category_path(@ladies.id)
    %section.items-box-container.clearfix
      %h3.items-box-container__title
        = link_to "#{@mens.name} 新着アイテム", category_path(@mens.id)
      .items-box-content.clearfix
        = render partial: "product", collection: @mens_item
      .view-all
        = link_to "すべての商品を見る", category_path(@mens.id)
    %section.items-box-container.clearfix
      %h3.items-box-container__title
        = link_to "#{@baby.name} 新着アイテム", category_path(@mens.id)
      .items-box-content.clearfix
        = render partial: "product", collection: @baby_item
      .view-all
        = link_to "すべての商品を見る", category_path(@mens.id)
    %section.items-box-container.clearfix
      %h3.items-box-container__title
        = link_to "#{@cosme.name} 新着アイテム", category_path(@mens.id)
      .items-box-content.clearfix
        = render partial: "product", collection: @cosme_item
      .view-all
        = link_to "すべての商品を見る", category_path(@mens.id)
    %h2.pickup-head ピックアップブランド
    %section.items-box-container.clearfix
      %h3.items-box-container__title
        = link_to "#{@chanel.name} 新着アイテム", brand_path(@chanel.id)
      .items-box-content.clearfix
        = render partial: "product", collection: @chanel_item
      .view-all
        = link_to "すべての商品を見る", brand_path(@chanel.id)
    %section.items-box-container.clearfix
      %h3.items-box-container__title
        = link_to "#{@vuitton.name} 新着アイテム", brand_path(@vuitton.id)
      .items-box-content.clearfix
        = render partial: "product", collection: @vuitton_item
      .view-all
        = link_to "すべての商品を見る", brand_path(@vuitton.id)
    %section.items-box-container.clearfix
      %h3.items-box-container__title
        = link_to "#{@supreme.name} 新着アイテム", brand_path(@supreme.id)
      .items-box-content.clearfix
        = render partial: "product", collection: @supreme_item
      .view-all
        = link_to "すべての商品を見る", brand_path(@supreme.id)
    %section.items-box-container.clearfix
      %h3.items-box-container__title
        = link_to "#{@nike.name} 新着アイテム", brand_path(@nike.id)
      .items-box-content.clearfix
        = render partial: "product", collection: @nike_item
      .view-all
        = link_to "すべての商品を見る", brand_path(@nike.id)

  = render 'shared/appbanner'

  = render 'shared/footer'

  = render 'shared/sellbtn'

app/views/products/search.html.haml
.default-container

  = render 'shared/header'

  %section.search-result-container.clearfix
    %div.search-box
      = sort_link(@search, :price, "価格")
      = sort_link(@search, :created_at, "新着順")
      .search-box__detail-search
        %h1.search-box__detail-search__title
          詳細検索
        = search_form_for @search, url: search_products_path do |f|
          .search-box__detail-search__form-group
            = f.label :name_cont, class: "search-box__detail-search__form-group__label" do
              = fa_icon "plus", text: "キーワードを追加する"
            = f.search_field :name_cont, class: "search-box__detail-search__form-group__input"
          .search-box__detail-search__form-group
            = f.label :category_id, class: "search-box__detail-search__form-group__label" do
              = fa_icon "list", text: "カテゴリーを選択する"
            = f.collection_select :category_id, Category.main_category, :id, :name, {include_blank: 'すべて'}, { class: "search-box__detail-search__form-group__input" }
          .search-box__detail-search__form-group
            = f.label :brand_cont, class: "search-box__detail-search__form-group__label" do
              = fa_icon "tag", text: "ブランド名から探す"
            = f.search_field :brand_name_cont, class: "search-box__detail-search__form-group__input"
          .search-box__detail-search__form-group
            = f.label :size_id_eq, class: "search-box__detail-search__form-group__label" do
              = fa_icon "square-o", text: "サイズを指定する"
            = f.collection_select :product_size_id_eq, ProductSize.all, :id, :size, { include_blank: 'すべて'}, { class: "search-box__detail-search__form-group__input" }
          .search-box__detail-search__form-group
            = f.label :Price, class: "search-box__detail-search__form-group__label" do
              = fa_icon "yen", text: "価格"
            .search-box__detail-search__form-group__price-box.clearfix
              = f.number_field :price_gteq, placeholder: "￥ Min", class: "search-box__detail-search__form-group__price-min search-box__detail-search__form-group__input"
              .search-box__detail-search__form-group__price-between
                〜
              = f.number_field :price_lteq, placeholder: "￥ Max", class: "search-box__detail-search__form-group__price-max search-box__detail-search__form-group__input"
          .search-box__detail-search__form-group
            = f.label :condition_in, class: "search-box__detail-search__form-group__label" do
              = fa_icon "star", text: "商品の状態"
            = f.collection_check_boxes :condition_in, Product.conditions, :last, :first do |b|
              = b.label class: "search-box__detail-search__form-group__checkbox" do
                = b.check_box
                = b.text
          .search-box__detail-search__form-group
            = f.label :shipping_burden_in, class: "search-box__detail-search__form-group__label" do
              = fa_icon "car", text: "配送料の負担"
            = f.collection_check_boxes :shipping_burden_in, Product.shipping_burdens, :last, :first do |b|
              = b.label class: "search-box__detail-search__form-group__checkbox" do
                = b.check_box
                = b.text
          .search-box__detail-search__form-group
            = f.label :name_or_description_cont, class: "search-box__detail-search__form-group__label" do
              = fa_icon "shopping-basket", text: "販売状況"
            .clearfix
              = f.check_box :status_eq, { class: "search-box__detail-search__form-group__status-checkbox" } , checked_value = 0, unchecked_value = ""
              .search-box__detail-search__form-group__status-name
                出品中
            .clearfix
              = f.check_box :status_eq, { class: "search-box__detail-search__form-group__status-checkbox" }, checked_value = 3, unchecked_value = ""
              .search-box__detail-search__form-group__status-name
                売り切れ
          .search-box__detail-search__form-group--box.clearfix
            %button.search-box__detail-search__form-group__clear
              クリア
            = f.submit '検索', class: "search-box__detail-search__form-group__search"
    %div.search-result.clearfix
      - if @products
        - if @products.length > 0
          %h1.search-result__title 検索結果#{@products.length}件
          - @products.each do |product|
            %div.search-result__item-box
              = link_to product_path(product), class: "search-result-image" do
                = image_tag product.product_images.first.image ,class: "search-result-image"
              .search-result__item-box--body
                %h3.search-result__item-box--body-name
                  = product.name
                %h3.search-result__item-box--body-price
                  ¥
                  = number_with_delimiter("#{product.price}")
                .item-details__tax
                  (税込み)
        - else
          %h1.search-result__title
            検索結果 0件
          %p.search-result__info
            該当する商品が見つかりません。商品は毎日増えていますので、これからの出品に期待してください。
      - else
        %h1.search-result__title
          検索結果 0件
        %p.search-result__info
          該当する商品が見つかりません。商品は毎日増えていますので、これからの出品に期待してください。

  = render 'shared/appbanner'

  = render 'shared/footer'

  = render 'shared/sellbtn'

app/views/products/show.html.haml
= render 'shared/header'
- breadcrumb :show_products, @product
%nav.bread-crumbs
  = breadcrumbs separator: " #{content_tag(:i, '', :class=>'fa fa-angle-right')} "
%section.product-page-detail
  %h1.product-page-detail__title
    = @product.name
  .product-page-detail__main.product-page-main.clearfix
    .product-page-main__images
      = image_tag @product.product_images[0].image ,class: "items-box__image1", class: "product-page-main__images--main"
      - if @product.sold?
        .product-page-main__images--soldout-badge
        .product-page-main__images--soldout
          SOLD
      - if @product.stopped?
        .product-page-main__images--stopped-badge
        .product-page-main__images--stopped
          出品停止中
      .product-page-main__images--others.clearfix
        - @product.product_images.each do |product_image|
          = image_tag product_image.image, class: "items-box__image1", class: "other-image"
        .other-image-masks.clearfix
          - 10.times do
            .other-image-masks__mask
    %table.product-page-main__details
      %tbody.item-detail-table
        %tr.item-detail-table__record
          %th.item-detail-table__record--key
            出品者
          %td.item-detail-table__record--value
            = link_to @product.user.nickname, ""
            .user-raitings.clearfix
              .user-raitings__raiting
                = fa_icon "smile lg", text:0
              .user-raitings__raiting
                = fa_icon "meh lg", text:0
              .user-raitings__raiting
                = fa_icon "frown lg", text:0
        %tr.item-detail-table__record
          %th.item-detail-table__record--key
            カテゴリー
          %td.item-detail-table__record--value
            = link_to @product.category.main_category.name, category_path(@product.category.main_category.id), { class: "table-link" }
            = link_to category_path(@product.category.sub_category.id), {class: "table-link"} do
              = fa_icon "angle-right lg"
              = @product.category.sub_category.name
            = link_to category_path(@product.category.id), {class: "table-link"} do
              = fa_icon "angle-right lg"
              = @product.category.name

        %tr.item-detail-table__record
          %th.item-detail-table__record--key
            ブランド
          %td.item-detail-table__record--value
            - if !@product.brand_id.nil?
              = link_to @product.brand.name, brand_path(@product.brand.id), { class: "table-link" }
        %tr.item-detail-table__record
          %th.item-detail-table__record--key
            商品のサイズ
          %td.item-detail-table__record--value
            = @product.product_size.size
        %tr.item-detail-table__record
          %th.item-detail-table__record--key
            商品の状態
          %td.item-detail-table__record--value
            = @product.condition
        %tr.item-detail-table__record
          %th.item-detail-table__record--key
            配送料の負担
          %td.item-detail-table__record--value
            = @product.shipping_burden
        %tr.item-detail-table__record
          %th.item-detail-table__record--key
            配送の方法
          %td.item-detail-table__record--value
            = @product.shipping_method
        %tr.item-detail-table__record
          %th.item-detail-table__record--key
            配送元地域
          %td.item-detail-table__record--value
            = link_to @product.area.prefecture, "", { class: "table-link" }
        %tr.item-detail-table__record
          %th.item-detail-table__record--key
            発送日の目安
          %td.item-detail-table__record--value
            = @product.estimated_date
  .product-page-detail__price
    %span.product-page-detail__price--price
      ￥
      = number_with_delimiter(@product.price)
    %span.product-page-detail__price--tax
      (税込)
    %span.product-page-detail__price--shipping-fee
      = @product.shipping_burden.sub(/\(.*/, "")
  - if @product.user == current_user
    - if @product.published?
      = link_to edit_product_path(@product), class: "product-page-detail__edit-button" do
        商品の編集
      .product-page-detail__or
        or
      = link_to stop_product_path(@product), method: :post, class: "product-page-detail__stop-button" do
        出品を一旦停止にする
      = link_to product_path(@product), method: :delete, class: "product-page-detail__delete-button" do
        商品を削除する
    - elsif @product.stopped?
      = link_to edit_product_path(@product), class: "product-page-detail__edit-button" do
        商品の編集
      .product-page-detail__or
        or
      = link_to start_product_path(@product), method: :post, class: "product-page-detail__stop-button--active" do
        出品を再開にする
      = link_to product_path(@product), method: :delete, class: "product-page-detail__delete-button" do
        商品を削除する
    - else
      .product-page-detail__buy-button--soldout
        売り切れました
  - else
    - if @product.published?
      = link_to new_product_purchase_path(@product), class: "product-page-detail__buy-button" do
        購入画面に進む
    - else
      .product-page-detail__buy-button--soldout
        売り切れました
  .product-page-detail__description
    = @product.description
  .product-page-detail__buttons
    = button_tag "", class: "product-page-detail__buttons--liked" do
      = fa_icon "heart lg"
      %span
        いいね!
      %span
        189
    = link_to "", class: "product-page-detail__buttons--report" do
      = fa_icon "flag lg"
      %span
        不適切な商品の報告
    .product-page-detail__buttons--safe
      = link_to "" do
        = fa_icon "lock lg", text:"あんしん・あんぜんへの取り組み"

.product-page-comment
  .message-content
    %ul.product-page-comment__messages.item-messages
      %li.item-messages__message.clearfix
        .item-messages__message--user
          = link_to "" do
            %figure.message-user
              .message-user__image
                = image_tag "https://img.buzzfeed.com/buzzfeed-static/static/2018-01/19/4/enhanced/buzzfeed-prod-fastlane-01/longform-original-6927-1516353932-3.jpg?downsize=1600:*&output-format=auto&output-quality=auto"
              %figcaption.message-user__name
                石原
        .item-messages__message--body.message-body
          .message-body__text
            こんにちは！無料で譲っていただけませんか？
          .message-body__icons
            =fa_icon "clock lg", text:"６日前"
      %li.item-messages__message.clearfix
        .item-messages__message--user
          = link_to "" do
            %figure.message-user
              .message-user__image
                = image_tag "https://upload.wikimedia.org/wikipedia/commons/9/9e/Ours_brun_parcanimalierpyrenees_1.jpg"
              %figcaption.message-user__name
                市川
        .item-messages__message--body.message-body
          .message-body__text
            無理です！
          .message-body__icons
            =fa_icon "clock lg", text:"５日前"
  .massege-content
    .product-page-comment__attention
      相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
    %textarea.product-page-comment__textarea
    = button_tag "", class: "product-page-comment__submit" do
      %span
        コメントする

%ul.product-page-prev-next-link.clearfix
  %li.product-page-prev-next-link__prev
    - if !@other_product_previous.nil?
      = link_to product_path(@other_product_previous.id), class: "clearfix" do
        = fa_icon "angle-left lg", class: "product-page-prev-next-link__prev--icon"
        %span.product-page-prev-next-link__prev--item-name
          = @other_product_previous.name
  %li.product-page-prev-next-link__next
    - if !@other_product_next.nil?
      = link_to product_path(@other_product_next.id), class: "clearfix"  do
        = fa_icon "angle-right lg", class: "product-page-prev-next-link__next--icon"
        %span.product-page-prev-next-link__next--item-name
          = @other_product_next.name

- if !@user_other_products.blank?
  %section.product-page-assosiation-items
    = link_to "" do
      %h2.section.product-page-assosiation-items__title
        = @product.user.nickname + "さんのその他の商品"
    .clearfix
      - @user_other_products.each do |user_other_product|
        = link_to product_path(user_other_product.id), class: "product-page-assosiation-items__items-box items-box" do
          = image_tag user_other_product.product_images[0].image ,class: "items-box__image"
          .items-box__body
            .items-box__body--details.item-details.clearfix
              %h3.item-details__name
                = user_other_product.name
              .item-details__num.clearfix
                .item-details__num--price
                  ￥
                  = number_with_delimiter(user_other_product.price)
                .item-details__num--liked
                  = fa_icon "heart-o", text:"189"
              .item-details__tax
                (税込)

- if !@product.brand_id.nil?
  - if !@other_products.blank?
    %section.product-page-assosiation-items
      = link_to "" do
        %h2.section.product-page-assosiation-items__title
          = @product.brand.name + "の" + @product.category.sub_category.name + "その他の商品"
      .clearfix
        - @other_products.each do |other_product|
          = link_to product_path(other_product.id), class: "product-page-assosiation-items__items-box items-box" do
            = image_tag other_product.product_images[0].image ,class: "items-box__image"
            .items-box__body
              .items-box__body--details.item-details.clearfix
                %h3.item-details__name
                  = other_product.name
                .item-details__num.clearfix
                  .item-details__num--price
                    ￥
                    = number_with_delimiter(other_product.price)
                  .item-details__num--liked
                    = fa_icon "heart-o", text:"189"
                .item-details__tax
                  (税込)

- else
  - if !@other_products_no_brand.blank?
    %section.product-page-assosiation-items
      = link_to "" do
        %h2.section.product-page-assosiation-items__title
          = @product.category.sub_category.name + "その他の商品"
      .clearfix
        - @other_products_no_brand.each do |other_product_no_brand|
          = link_to product_path(other_product_no_brand.id), class: "product-page-assosiation-items__items-box items-box" do
            = image_tag other_product_no_brand.product_images[0].image ,class: "items-box__image"
            .items-box__body
              .items-box__body--details.item-details.clearfix
                %h3.item-details__name
                  = other_product_no_brand.name
                .item-details__num.clearfix
                  .item-details__num--price
                    ￥
                    = number_with_delimiter(other_product_no_brand.price)
                  .item-details__num--liked
                    = fa_icon "heart-o", text:"189"
                .item-details__tax
                  (税込)

= render 'shared/appbanner'
= render 'shared/footer'